In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("C:/Users/Lenovo/Online_Retail.xlsx", engine='openpyxl')

In [9]:
print(df.head(10))

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6
7    536366     22633               HAND WARMER UNION JACK         6
8    536366     22632            HAND WARMER RED POLKA DOT         6
9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
5 2010-12-01 08:26:00       7.65     17850.0  United Kingdom
6 2010-12-01 08:26:00       4.25     17850.0  United Kingdom
7 2010-12-01 08:28:00       1.85     17850.0  United Kingdom
8 2010-12-01 08:28:00       1.85     17850.0  United Kingdom
9 2010-12-01 08:34:00       1.69     13047.0  United Kingdom

In [6]:
df.tail(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [10]:
df.shape

(541909, 8)

In [ ]:
#EXPLORE DATA

In [7]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [11]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(5268)

In [13]:
#DATA CLEANING

In [19]:
df = df.dropna(subset=['CustomerID']) # removing missing Customer ID 
df = df.drop_duplicates() # removing duplicated data
df = df[df['Quantity']>0] # removing negetive or zero quantity

In [21]:
df['InvoiceDate']= pd.to_datetime(df['InvoiceDate']) #converting date
df['TotalPrice'] = df['Quantity']*df['UnitPrice'] #Create TotalPrice

In [22]:
df['TotalPrice']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: TotalPrice, Length: 392732, dtype: float64

In [ ]:
#feature engineering

In [23]:
df['month'] = df['InvoiceDate'].dt.month # Extract month (for future analysis)
df['Day'] = df['InvoiceDate'].dt.day # Extract day

In [24]:
#RFM Analysis

In [26]:
import datetime as dt
today = df['InvoiceDate'].max() + dt.timedelta(days=1)
rfm = df.groupby('CustomerID').agg({
    'InvoiceDate':lambda x:(today -x.max()).days,
    'InvoiceNo':'count',
    'TotalPrice':'sum'
})
rfm.columns=['Recency','Frequency','Monetary']

In [27]:
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         326          1  77183.60
12347.0           2        182   4310.00
12348.0          75         31   1797.24
12349.0          19         73   1757.55
12350.0         310         17    334.40

In [28]:
#Basic insights
rfm.describe()

           Recency    Frequency       Monetary
count  4339.000000  4339.000000    4339.000000
mean     92.518322    90.512100    2048.215924
std     100.009747   225.515328    8984.248352
min       1.000000     1.000000       0.000000
25%      18.000000    17.000000     306.455000
50%      51.000000    41.000000     668.560000
75%     142.000000    98.000000    1660.315000
max     374.000000  7676.000000  280206.020000

In [ ]:
# save outputs

In [30]:
import os
os.makedirs("outputs",exist_ok = True)
rfm.to_csv("outputs/rfm_data.csv")